definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
  v1.FinanceByOrderIDQueryRequestBody:
    properties:
      OrderID:
        description: 对应订单号
        type: string
    type: object
  v1.FinanceByStatusQueryRequestBody:
    properties:
      Status:
        description: 融资状态
        type: string
    type: object
  v1.FinanceBySupplierQueryRequestBody:
    properties:
      Supplier:
        description: 申请人
        type: string
    type: object
  v1.FinanceRequestBody:
    properties:
      Amount:
        description: 申请金额
        type: string
      Desc:
        description: 申请描述
        type: string
      Feedback:
        description: 融资反馈
        type: string
      OrderID:
        description: 对应订单号
        type: string
      Period:
        description: 申请日期
        type: string
      Status:
        description: 融资状态
        type: string
      Supplier:
        description: 申请人
        type: string
    type: object
  v1.OrderByBuyerQueryRequestBody:
    properties:
      Buyer:
        description: 发起企业
        type: string
    type: object
  v1.OrderByIDQueryRequestBody:
    properties:
      ID:
        description: 订单ID
        type: string
    type: object
  v1.OrderBySellerQueryRequestBody:
    properties:
      Seller:
        description: 供货商
        type: string
    type: object
  v1.OrderRequestBody:
    properties:
      Address:
        description: 收货地址
        type: string
      Buyer:
        description: 发起企业
        type: string
      BuyerID:
        description: 企业ID
        type: string
      CreateTime:
        description: 创建时间
        type: string
      Deadline:
        description: 截止日期
        type: string
      GoodsID:
        description: 货品ID
        type: string
      GoodsName:
        description: 货品名称
        type: string
      GoodsNum:
        description: 货品数量
        type: string
      ID:
        description: 订单ID
        type: string
      OrderAmount:
        description: 订单总金额
        type: string
      Remark:
        description: 备注
        type: string
      Seller:
        description: 供货商
        type: string
      SellerID:
        description: 供应商ID
        type: string
      Status:
        description: 订单状态
        type: string
      TransferID:
        description: 物流ID
        type: string
      Transferstatus:
        description: 物流状态
        type: string
    type: object
  v1.ProductByAmountUpdateRequestBody:
    properties:
      Amount:
        description: 货品数量
        type: integer
      GoodsID:
        description: 货品ID
        type: string
    type: object
  v1.ProductByGoodTypeQueryRequestBody:
    properties:
      GoodType:
        description: 货品类型
        type: string
    type: object
  v1.ProductByMaterialQueryRequestBody:
    properties:
      Material:
        description: 材料
        type: string
    type: object
  v1.ProductByNameQueryRequestBody:
    properties:
      GoodsID:
        description: 货品ID
        type: string
    type: object
  v1.ProductBySupplierQueryRequestBody:
    properties:
      Supplier:
        description: 供应商
        type: string
    type: object
  v1.ProductByWorkmanshipQueryRequestBody:
    properties:
      Workmanship:
        description: 制作工艺
        type: string
    type: object
  v1.ProductRequestBody:
    properties:
      AddDate:
        description: 上架时间
        type: string
      Amount:
        description: 货品数量
        type: integer
      GoodType:
        description: 货品类型
        type: integer
      GoodsID:
        description: 货品ID
        type: string
      Material:
        description: 材料
        type: string
      Name:
        description: 货品名称
        type: string
      Price:
        description: 价格
        type: integer
      Remark:
        description: 备注
        type: string
      ShippingArea:
        description: 发货地区
        type: string
      Standards:
        description: 规格
        type: string
      Supplier:
        description: 供应商
        type: string
      SupplierID:
        type: string
      Tel:
        description: 联系方式
        type: string
      Workmanship:
        description: 制作工艺
        type: string
    type: object
  v1.UpdateOrderStatusRequestBody:
    properties:
      ID:
        description: 订单ID
        type: string
      Status:
        description: 订单状态
        type: string
    type: object
  v1.UpdateStatusRequestBody:
    properties:
      OrderID:
        description: 对应订单号
        type: string
      Period:
        description: 申请日期
        type: string
      Status:
        description: 融资状态
        type: string
    type: object
  v1.UpdateTransferStatusRequestBody:
    properties:
      ID:
        description: 订单ID
        type: string
      TransferID:
        description: 物流ID
        type: string
      Transferstatus:
        description: 物流状态
        type: string
    type: object
  v1.User:
    properties:
      ID:
        description: ID
        type: string
      account:
        description: 账号
        type: string
      identity:
        description: 身份
        type: string
      name:
        description: 具体名字
        type: string
      password:
        description: 密码
        type: string
    type: object
  v1.UserByIDQueryRequestBody:
    properties:
      account:
        description: 账号
        type: string
      password:
        description: 密码
        type: string
    type: object
info:
  contact:
    email: 144240096@qq.com
    name: togettoyou
  description: 基于区块链的钢材供应链融资解决方案api文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: 基于区块链的钢材供应链融资解决方案
  version: "1.0"
paths:
  /api/v1/DeleteOrder:
    post:
      parameters:
      - description: Order
        in: body
        name: Order
        required: true
        schema:
          $ref: '#/definitions/v1.OrderByIDQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 更改订单状态
  /api/v1/DeleteProduct:
    post:
      parameters:
      - description: Product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/v1.ProductByNameQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 更改订单状态
  /api/v1/QueryFinance:
    post:
      parameters:
      - description: Finance
        in: body
        name: Finance
        required: true
        schema:
          $ref: '#/definitions/v1.ProductByNameQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 查询所有
  /api/v1/QueryFinanceByOrderID:
    post:
      parameters:
      - description: Finance
        in: body
        name: Finance
        required: true
        schema:
          $ref: '#/definitions/v1.FinanceByOrderIDQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按订单号查询
  /api/v1/QueryFinanceByStatus:
    post:
      parameters:
      - description: Finance
        in: body
        name: Finance
        required: true
        schema:
          $ref: '#/definitions/v1.FinanceByStatusQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按融资状态查询
  /api/v1/QueryFinanceBySupplier:
    post:
      parameters:
      - description: Finance
        in: body
        name: Finance
        required: true
        schema:
          $ref: '#/definitions/v1.FinanceBySupplierQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 查询所有
  /api/v1/QueryOrder:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 查询全部订单
  /api/v1/QueryOrderByBuyer:
    post:
      parameters:
      - description: Order
        in: body
        name: Order
        required: true
        schema:
          $ref: '#/definitions/v1.OrderByBuyerQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按发起企业查询订单内容
  /api/v1/QueryOrderByID:
    post:
      parameters:
      - description: Order
        in: body
        name: Order
        required: true
        schema:
          $ref: '#/definitions/v1.OrderByIDQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按订单ID查询，具体查询某一个订单
  /api/v1/QueryOrderByIDTest:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 测试：按订单ID查询，具体查询某一个订单
  /api/v1/QueryOrderBySeller:
    post:
      parameters:
      - description: Order
        in: body
        name: Order
        required: true
        schema:
          $ref: '#/definitions/v1.OrderBySellerQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按供货商查询订单内容
  /api/v1/QueryProduct:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 查询全部货品
  /api/v1/QueryProductByGoodType:
    post:
      parameters:
      - description: Product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/v1.ProductByGoodTypeQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按货品类型查询
  /api/v1/QueryProductByID:
    post:
      parameters:
      - description: Product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/v1.ProductByNameQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按货品ID查询
  /api/v1/QueryProductByMaterial:
    post:
      parameters:
      - description: Product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/v1.ProductByMaterialQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按材料查询
  /api/v1/QueryProductBySupplier:
    post:
      parameters:
      - description: Product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/v1.ProductBySupplierQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按供应商查询
  /api/v1/QueryProductByWorkmanship:
    post:
      parameters:
      - description: Product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/v1.ProductByWorkmanshipQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 按制作工艺查询
  /api/v1/QueryUser:
    post:
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.UserByIDQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 根据账号查询
  /api/v1/QueryUserTest:
    post:
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.UserByIDQueryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 根据账号查询
  /api/v1/QueryUserTestGet:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 根据账号查询
  /api/v1/StoreFinance:
    post:
      parameters:
      - description: Finance
        in: body
        name: Finance
        required: true
        schema:
          $ref: '#/definitions/v1.FinanceRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 存储到数据库
  /api/v1/StoreOrder:
    post:
      parameters:
      - description: user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 存储到数据库
  /api/v1/StoreProduct:
    post:
      parameters:
      - description: Product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/v1.ProductRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 存储到数据库
  /api/v1/UpdateFinanceStatus:
    post:
      parameters:
      - description: Finance
        in: body
        name: Finance
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateStatusRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 更新融资状态
  /api/v1/UpdateProductByAmount:
    post:
      parameters:
      - description: Product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/v1.ProductByAmountUpdateRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 更新货品数量
  /api/v1/UpdateStatus:
    post:
      parameters:
      - description: Order
        in: body
        name: Order
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateOrderStatusRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 更新是否接收状态
  /api/v1/UpdateTransferStatus:
    post:
      parameters:
      - description: Order
        in: body
        name: Order
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateTransferStatusRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 更新订单物流状态状态
swagger: "2.0"
